site_name: Java Tron
site_url: https://ferdinand026.github.io/documentation-zh/
theme: 
    name: material
    features:
        - navigation.expand # 导航目录默认全部展开
        - navigation.indexes
        - navigation.tabs # 顶部导航栏以 Tab 形式展示
        - navigation.sections
        - toc.follow
        - toc.integrate
    hide:
        - navigation.footer
markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长
plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 简体中文
          build: true

