site_name: Java Tron

nav:
    - 简体中文:
        - 主页: zh/index.md
        - 使用指南: zh/guide.md
    - English:
      - Home: en/index.md
      - Guide: en/guide.md

theme: 
    name: material
    language: zh
    features:
        - navigation.tracing  # 页面滚动时左侧导航高亮跟踪位置
        - navigation.expand # 导航目录默认全部展开
        - navigation.tabs # 顶部导航栏以 Tab 形式展示
    hide:
    - navigation.footer
markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长
plugins:
  - search
  - i18n:
      default_language: zh
      languages:
        zh: 简体中文
        en: English
