site_name: Java Tron
site_url: https://ferdinand026.github.io/documentation-zh/
use_directory_urls: false  # 防止路径嵌套异常
theme: 
    name: material
    features:
        - navigation.tracing  # 页面滚动时左侧导航高亮跟踪位置
        - navigation.expand # 导航目录默认全部展开
        - navigation.tabs # 顶部导航栏以 Tab 形式展示
    hide:
    - navigation.footer
markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长
plugins:
  - search
  - i18n:
      default_language: zh
      default_language_only: true
      languages:
        - locale: zh
          name: 简体中文
          default: true
          build: true
        - locale: en
          name: English
          build: true

nav:
  - 简体中文:
      - 主页: zh/index.md
  - English:
      - Home: en/index.md
      - Getting Started With java-tron:
          - Getting Started: en/getting_started/getting_started_with_javatron.md
      - Using java-tron:
          - Deploying: en/using_javatron/installing_javatron.md
          - Backup and Restore: en/using_javatron/backup_restore.md
          - Lite FullNode: en/using_javatron/litefullnode.md
          - Private Network: en/using_javatron/private_network.md
          - Event Subscription: en/architecture/event.md
          - Database Configuration: en/architecture/database.md
          - Network Connection: en/using_javatron/connecting_to_tron.md
          - Node Monitoring: en/using_javatron/metrics.md
          - Node Maintenance Tool: en/using_javatron/toolkit.md
      - API:
          - HTTP API: en/api/http.md
          - gRPC API: en/api/rpc.md
          - jsonRPC API: en/api/json-rpc.md
      - Core Protocol:
          - DPoS: en/mechanism-algorithm/dpos.md
          - Super Representative: en/mechanism-algorithm/sr.md
          - Account Model: en/mechanism-algorithm/account.md
          - Resource Model: en/mechanism-algorithm/resource.md
          - Smart Contract: en/contracts/contract.md
          - System Contract: en/mechanism-algorithm/system-contracts.md
          - Decentralized Exchange: en/mechanism-algorithm/dex.md
          - Account Permission Management: en/mechanism-algorithm/multi-signatures.md
      - For java-tron Developers:
          - Developer Guide: en/developers/java-tron.md
      - For Dapp Developers:
          - Tools: en/contracts/tools.md
