site_name: Java Tron

theme: 
    name: material
    features:
        - navigation.tracing  # 页面滚动时左侧导航高亮跟踪位置
        - navigation.expand # 导航目录默认全部展开
        - navigation.tabs # 顶部导航栏以 Tab 形式展示
    hide:
    - navigation.footer
markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长
plugins:
  - search
  - i18n:
      default_language: zh
      languages:
        - locale: zh
          name: 简体中文
          default: true
          build: true
        - locale: en
          name: English
          build: true

nav:
  - 简体中文:
      - 主页: zh/index.md
  - English:
      - Home: index.md
      - Getting Started With java-tron:
          - Getting Started: getting_started/getting_started_with_javatron.md
      - Using java-tron:
          - Deploying: using_javatron/installing_javatron.md
          - Backup and Restore: using_javatron/backup_restore.md
          - Lite FullNode: using_javatron/litefullnode.md
          - Private Network: using_javatron/private_network.md
          - Event Subscription: architecture/event.md
          - Database Configuration: architecture/database.md
          - Network Connection: using_javatron/connecting_to_tron.md
          - Node Monitoring: using_javatron/metrics.md
          - Node Maintenance Tool: using_javatron/toolkit.md
      - API:
          - HTTP API: api/http.md
          - gRPC API: api/rpc.md
          - jsonRPC API: api/json-rpc.md
      - Core Protocol:
          - DPoS: mechanism-algorithm/dpos.md
          - Super Representative: mechanism-algorithm/sr.md
          - Account Model: mechanism-algorithm/account.md
          - Resource Model: mechanism-algorithm/resource.md
          - Smart Contract: contracts/contract.md
          - System Contract: mechanism-algorithm/system-contracts.md
          - Decentralized Exchange: mechanism-algorithm/dex.md
          - Account Permission Management: mechanism-algorithm/multi-signatures.md
      - For java-tron Developers:
          - Developer Guide: developers/java-tron.md
          - TIPs Workflow: developers/tips.md
          - Issue Workflow: developers/issue-workflow.md
          - Governance Workflow: developers/governance.md
          - Configure the IDE: developers/run-in-idea.md
          - Development Example: developers/demo.md
          - Core Modules: developers/code-structure.md
      - For Dapp Developers:
          - Tools: contracts/tools.md
      - Clients:
          - wallet-cli: clients/wallet-cli.md
      - Releases:
          - Deployment Manual for the New Version: releases/upgrade-instruction.md
          - Integrity Check: releases/signature_verification.md
          - History: releases/history.md
      - Appendix:
          - Glossary: glossary.md
