site_name: Java Tron
site_url: https://ferdinand026.github.io/documentation-zh/
theme: 
    name: material
    features:
        - navigation.expand # 导航目录默认全部展开
        - navigation.indexes
        - navigation.tabs # 顶部导航栏以 Tab 形式展示
        - navigation.sections
        - toc.follow
        - toc.integrate
    hide:
        - navigation.footer
markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长
plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 简体中文
          build: true

nav:
  - 主页: zh/index.md
  - java-tron入门: 
      - 入门: zh/getting_started/getting_started_with_javatron.md
  - 使用java-tron:
      - 部署: zh/using_javatron/installing_javatron.md
      - 备份和恢复: zh/using_javatron/backup_restore.md
      - 轻节点: zh/using_javatron/litefullnode.md
      - 私链网络: zh/using_javatron/private_network.md
      - 事件订阅: zh/architecture/event.md
      - 数据库配置: zh/architecture/database.md
      - 网络连接: zh/using_javatron/connecting_to_tron.md
      - 节点监控: zh/using_javatron/metrics.md
      - 节点维护工具: zh/using_javatron/toolkit.md
  - API接口:
      - HTTP 接口: zh/api/http.md
      - gRPC 接口: zh/api/rpc.md
      - jsonRPC 接口: zh/api/json-rpc.md
  - 核心协议:
      - 波场共识: zh/mechanism-algorithm/dpos.md
      - 超级代表: zh/mechanism-algorithm/sr.md
      - 账户模型: zh/mechanism-algorithm/account.md
      - 资源模型: zh/mechanism-algorithm/resource.md
      - 智能合约: zh/contracts/contract.md
      - 系统合约: zh/mechanism-algorithm/system-contracts.md
      - 去中心化交易所: zh/mechanism-algorithm/dex.md
      - 账户权限管理: zh/mechanism-algorithm/multi-signatures.md
  - java-tron开发: 
      - 开发者指南: zh/developers/java-tron.md
      - TIPs工作流程: zh/developers/tips.md
      - Issue工作流程: zh/developers/issue-workflow.md
      - 治理流程: zh/developers/governance.md
      - 配置IDE开发环境: zh/developers/run-in-idea.md
      - 开发示例: zh/developers/demo.md
      - 核心模块: zh/developers/code-structure.md
  - Dapp开发:
      - 工具: zh/contracts/tools.md
  - 客户端: 
      - wallet-cli: zh/clients/wallet-cli.md
  - 版本发布:
      - 新版本部署手册: zh/releases/upgrade-instruction.md
      - 一致性检验: zh/releases/signature_verification.md
      - 历史版本: zh/releases/history.md
  - 附录: 
      - 术语表: zh/glossary.md
  - Home: en/index.md
  - Getting Started With java-tron:
      - Getting Started: en/getting_started/getting_started_with_javatron.md
  - Using java-tron:
      - Deploying: en/using_javatron/installing_javatron.md
      - Backup and Restore: en/using_javatron/backup_restore.md
      - Lite FullNode: en/using_javatron/litefullnode.md
      - Private Network: en/using_javatron/private_network.md
      - Event Subscription: en/architecture/event.md
      - Database Configuration: en/architecture/database.md
      - Network Connection: en/using_javatron/connecting_to_tron.md
      - Node Monitoring: en/using_javatron/metrics.md
      - Node Maintenance Tool: en/using_javatron/toolkit.md
  - API:
      - HTTP API: en/api/http.md
      - gRPC API: en/api/rpc.md
      - jsonRPC API: en/api/json-rpc.md
  - Core Protocol:
      - DPoS: en/mechanism-algorithm/dpos.md
      - Super Representative: en/mechanism-algorithm/sr.md
      - Account Model: en/mechanism-algorithm/account.md
      - Resource Model: en/mechanism-algorithm/resource.md
      - Smart Contract: en/contracts/contract.md
      - System Contract: en/mechanism-algorithm/system-contracts.md
      - Decentralized Exchange: en/mechanism-algorithm/dex.md
      - Account Permission Management: en/mechanism-algorithm/multi-signatures.md
  - For java-tron Developers:
      - Developer Guide: en/developers/java-tron.md
  - For Dapp Developers:
      - Tools: en/contracts/tools.md
