site_name: Java TronMore actions
site_url: https://tronprotocol.github.io/documentation-zh/
repo_url: https://github.com/tronprotocol/documentation-zh

nav:
    - Home: index.md
    - java-tron入门: 
        - 入门: getting_started/getting_started_with_javatron.md
    - 使用java-tron:
        - 部署: using_javatron/installing_javatron.md
        - 备份和恢复: using_javatron/backup_restore.md
theme: 
    name: material
    features:
        - navigation.tracing  # 页面滚动时左侧导航高亮跟踪位置
        - navigation.expand # 导航目录默认全部展开
        - navigation.tabs # 顶部导航栏以 Tab 形式展示
markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长
