nav:
  - 主页: zh/index.md
  - java-tron入门: 
      - 入门: zh/getting_started/getting_started_with_javatron.md
  - 使用java-tron:
      - 部署: zh/using_javatron/installing_javatron.md
      - 备份和恢复: zh/using_javatron/backup_restore.md
      - 轻节点: zh/using_javatron/litefullnode.md
      - 私链网络: zh/using_javatron/private_network.md
      - 事件订阅: zh/architecture/event.md
      - 数据库配置: zh/architecture/database.md
      - 网络连接: zh/using_javatron/connecting_to_tron.md
      - 节点监控: zh/using_javatron/metrics.md
      - 节点维护工具: zh/using_javatron/toolkit.md
  - API接口:
      - HTTP 接口: zh/api/http.md
      - gRPC 接口: zh/api/rpc.md
      - jsonRPC 接口: zh/api/json-rpc.md
  - 核心协议:
      - 波场共识: zh/mechanism-algorithm/dpos.md
      - 超级代表: zh/mechanism-algorithm/sr.md
      - 账户模型: zh/mechanism-algorithm/account.md
      - 资源模型: zh/mechanism-algorithm/resource.md
      - 智能合约: zh/contracts/contract.md
      - 系统合约: zh/mechanism-algorithm/system-contracts.md
      - 去中心化交易所: zh/mechanism-algorithm/dex.md
      - 账户权限管理: zh/mechanism-algorithm/multi-signatures.md
  - java-tron开发: 
      - 开发者指南: zh/developers/java-tron.md
      - TIPs工作流程: zh/developers/tips.md
      - Issue工作流程: zh/developers/issue-workflow.md
      - 治理流程: zh/developers/governance.md
      - 配置IDE开发环境: zh/developers/run-in-idea.md
      - 开发示例: zh/developers/demo.md
      - 核心模块: zh/developers/code-structure.md
  - Dapp开发:
      - 工具: zh/contracts/tools.md
  - 客户端: 
      - wallet-cli: zh/clients/wallet-cli.md
  - 版本发布:
      - 新版本部署手册: zh/releases/upgrade-instruction.md
      - 一致性检验: zh/releases/signature_verification.md
      - 历史版本: zh/releases/history.md
  - 附录: 
      - 术语表: zh/glossary.md
  