name: Test Publish Document

on:

  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger from GitHub UI


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygments==2.17.2 pymdown-extensions
        pip install mkdocs-exclude
        pip install mkdocs-material==9.6.8
        pip install jieba==0.42.1
        pip install mkdocs-static-i18n

    - name: Build the document
      run:  | 
        rm -rf site/
        mkdocs build
        mkdocs gh-deploy --force

    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: site # The folder the action should deploy.
